version: "3.5"
services:
    medical_db:
        image: "medical_db:latest"
        container_name: medical_db
        build:
            context: "./"
            dockerfile: "./Dockerfile"
        networks:
          - exercise_net
        ports:
            - "5000:5000"
        tty: true
networks:
    exercise_net:
        driver: bridge
