version: "3.5"
services:
    medical_db:
        image: "medical_db:latest"
        container_name: medical_db
        build:
            context: "./"
            dockerfile: "./Dockerfile"
        networks:
          - exercise_net
        ports:
            - "5000:5000"
        tty: true
    validate_medical_db:
        image: validate_medical_db:latest
        container_name: validate_medical_db
        build:
            context: "./test"
            dockerfile: Dockerfile
        volumes:
          - ./test/report:/app/logs 
        networks:
          - exercise_net
        tty: true
    unittest_medical_db:
        image: unittest_medical_db:latest
        container_name: unittest_medical_db
        build:
            context: "./"
            dockerfile: Dockerfile.unittest
        volumes:
          - ./logs:/app/logs
        command: /bin/sh -c "/app/run_tests.sh"
networks:
    exercise_net:
        driver: bridge
