# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define :centosmagma, autostart: false do |centosmagma|
    centosmagma.vm.hostname = "centos-magma"
    centosmagma.vm.network "private_network", ip: "192.168.60.180", nic_type: "82540EM"
    centosmagma.vm.network "private_network", ip: "192.168.129.78", nic_type: "82540EM"

    centosmagma.vm.provider "virtualbox" do |vb|
      vb.name = "centos-magma"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "6144"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end
