//
//Nudm_SDM
//
//Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
//
//The version of the OpenAPI document: 2.1.7
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0-devel
// 	protoc        v3.6.1
// source: additional_snssai_data.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdditionalSnssaiData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredAuthnAuthz bool `protobuf:"varint,73353388,opt,name=requiredAuthnAuthz,proto3" json:"requiredAuthnAuthz,omitempty"`
}

func (x *AdditionalSnssaiData) Reset() {
	*x = AdditionalSnssaiData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_additional_snssai_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdditionalSnssaiData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalSnssaiData) ProtoMessage() {}

func (x *AdditionalSnssaiData) ProtoReflect() protoreflect.Message {
	mi := &file_additional_snssai_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalSnssaiData.ProtoReflect.Descriptor instead.
func (*AdditionalSnssaiData) Descriptor() ([]byte, []int) {
	return file_additional_snssai_data_proto_rawDescGZIP(), []int{0}
}

func (x *AdditionalSnssaiData) GetRequiredAuthnAuthz() bool {
	if x != nil {
		return x.RequiredAuthnAuthz
	}
	return false
}

var File_additional_snssai_data_proto protoreflect.FileDescriptor

var file_additional_snssai_data_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x6e, 0x73,
	0x73, 0x61, 0x69, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x67, 0x6f, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x22, 0x49, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x6e, 0x73, 0x73, 0x61, 0x69, 0x44, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x12, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x18,
	0xac, 0x91, 0xfd, 0x22, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x42, 0x1a, 0x5a, 0x18,
	0x67, 0x6f, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_additional_snssai_data_proto_rawDescOnce sync.Once
	file_additional_snssai_data_proto_rawDescData = file_additional_snssai_data_proto_rawDesc
)

func file_additional_snssai_data_proto_rawDescGZIP() []byte {
	file_additional_snssai_data_proto_rawDescOnce.Do(func() {
		file_additional_snssai_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_additional_snssai_data_proto_rawDescData)
	})
	return file_additional_snssai_data_proto_rawDescData
}

var file_additional_snssai_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_additional_snssai_data_proto_goTypes = []interface{}{
	(*AdditionalSnssaiData)(nil), // 0: go_package.protos.AdditionalSnssaiData
}
var file_additional_snssai_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_additional_snssai_data_proto_init() }
func file_additional_snssai_data_proto_init() {
	if File_additional_snssai_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_additional_snssai_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdditionalSnssaiData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_additional_snssai_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_additional_snssai_data_proto_goTypes,
		DependencyIndexes: file_additional_snssai_data_proto_depIdxs,
		MessageInfos:      file_additional_snssai_data_proto_msgTypes,
	}.Build()
	File_additional_snssai_data_proto = out.File
	file_additional_snssai_data_proto_rawDesc = nil
	file_additional_snssai_data_proto_goTypes = nil
	file_additional_snssai_data_proto_depIdxs = nil
}
