//
//Nudm_SDM
//
//Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
//
//The version of the OpenAPI document: 2.1.7
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0-devel
// 	protoc        v3.6.1
// source: service_area_restriction.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceAreaRestriction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// RestrictionType restrictionType = 1397031;
	RestrictionType               string  `protobuf:"bytes,1397031,opt,name=restrictionType,proto3" json:"restrictionType,omitempty"`
	Areas                         []*Area `protobuf:"bytes,93077894,rep,name=areas,proto3" json:"areas,omitempty"`
	MaxNumOfTAs                   int32   `protobuf:"varint,128311309,opt,name=maxNumOfTAs,proto3" json:"maxNumOfTAs,omitempty"`
	MaxNumOfTAsForNotAllowedAreas int32   `protobuf:"varint,329639447,opt,name=maxNumOfTAsForNotAllowedAreas,proto3" json:"maxNumOfTAsForNotAllowedAreas,omitempty"`
}

func (x *ServiceAreaRestriction) Reset() {
	*x = ServiceAreaRestriction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_area_restriction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAreaRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAreaRestriction) ProtoMessage() {}

func (x *ServiceAreaRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_service_area_restriction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAreaRestriction.ProtoReflect.Descriptor instead.
func (*ServiceAreaRestriction) Descriptor() ([]byte, []int) {
	return file_service_area_restriction_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAreaRestriction) GetRestrictionType() string {
	if x != nil {
		return x.RestrictionType
	}
	return ""
}

func (x *ServiceAreaRestriction) GetAreas() []*Area {
	if x != nil {
		return x.Areas
	}
	return nil
}

func (x *ServiceAreaRestriction) GetMaxNumOfTAs() int32 {
	if x != nil {
		return x.MaxNumOfTAs
	}
	return 0
}

func (x *ServiceAreaRestriction) GetMaxNumOfTAsForNotAllowedAreas() int32 {
	if x != nil {
		return x.MaxNumOfTAsForNotAllowedAreas
	}
	return 0
}

var File_service_area_restriction_proto protoreflect.FileDescriptor

var file_service_area_restriction_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x72,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x67, 0x6f, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x1a, 0x0a, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe5, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x0f, 0x72, 0x65,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0xa7, 0xa2,
	0x55, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x18,
	0x86, 0x83, 0xb1, 0x2c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x12, 0x23, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x4e,
	0x75, 0x6d, 0x4f, 0x66, 0x54, 0x41, 0x73, 0x18, 0x8d, 0xc0, 0x97, 0x3d, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x6d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x54, 0x41, 0x73, 0x12, 0x48, 0x0a,
	0x1d, 0x6d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x54, 0x41, 0x73, 0x46, 0x6f, 0x72, 0x4e,
	0x6f, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x41, 0x72, 0x65, 0x61, 0x73, 0x18, 0x97,
	0xcc, 0x97, 0x9d, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x1d, 0x6d, 0x61, 0x78, 0x4e, 0x75, 0x6d,
	0x4f, 0x66, 0x54, 0x41, 0x73, 0x46, 0x6f, 0x72, 0x4e, 0x6f, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x41, 0x72, 0x65, 0x61, 0x73, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x6f, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_area_restriction_proto_rawDescOnce sync.Once
	file_service_area_restriction_proto_rawDescData = file_service_area_restriction_proto_rawDesc
)

func file_service_area_restriction_proto_rawDescGZIP() []byte {
	file_service_area_restriction_proto_rawDescOnce.Do(func() {
		file_service_area_restriction_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_area_restriction_proto_rawDescData)
	})
	return file_service_area_restriction_proto_rawDescData
}

var file_service_area_restriction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_area_restriction_proto_goTypes = []interface{}{
	(*ServiceAreaRestriction)(nil), // 0: go_package.protos.ServiceAreaRestriction
	(*Area)(nil),                   // 1: go_package.protos.Area
}
var file_service_area_restriction_proto_depIdxs = []int32{
	1, // 0: go_package.protos.ServiceAreaRestriction.areas:type_name -> go_package.protos.Area
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_area_restriction_proto_init() }
func file_service_area_restriction_proto_init() {
	if File_service_area_restriction_proto != nil {
		return
	}
	file_area_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_area_restriction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAreaRestriction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_area_restriction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_area_restriction_proto_goTypes,
		DependencyIndexes: file_service_area_restriction_proto_depIdxs,
		MessageInfos:      file_service_area_restriction_proto_msgTypes,
	}.Build()
	File_service_area_restriction_proto = out.File
	file_service_area_restriction_proto_rawDesc = nil
	file_service_area_restriction_proto_goTypes = nil
	file_service_area_restriction_proto_depIdxs = nil
}
