//
//Nudm_SDM
//
//Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
//
//The version of the OpenAPI document: 2.1.7
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0-devel
// 	protoc        v3.6.1
// source: snssai.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snssai struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sst int32  `protobuf:"varint,114196,opt,name=sst,proto3" json:"sst,omitempty"`
	Sd  string `protobuf:"bytes,3665,opt,name=sd,proto3" json:"sd,omitempty"`
}

func (x *Snssai) Reset() {
	*x = Snssai{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snssai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snssai) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snssai) ProtoMessage() {}

func (x *Snssai) ProtoReflect() protoreflect.Message {
	mi := &file_snssai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snssai.ProtoReflect.Descriptor instead.
func (*Snssai) Descriptor() ([]byte, []int) {
	return file_snssai_proto_rawDescGZIP(), []int{0}
}

func (x *Snssai) GetSst() int32 {
	if x != nil {
		return x.Sst
	}
	return 0
}

func (x *Snssai) GetSd() string {
	if x != nil {
		return x.Sd
	}
	return ""
}

var File_snssai_proto protoreflect.FileDescriptor

var file_snssai_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x6e, 0x73, 0x73, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x67, 0x6f, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x22, 0x2d, 0x0a, 0x06, 0x53, 0x6e, 0x73, 0x73, 0x61, 0x69, 0x12, 0x12, 0x0a, 0x03, 0x73,
	0x73, 0x74, 0x18, 0x94, 0xfc, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x73, 0x74, 0x12,
	0x0f, 0x0a, 0x02, 0x73, 0x64, 0x18, 0xd1, 0x1c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x64,
	0x42, 0x1a, 0x5a, 0x18, 0x67, 0x6f, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snssai_proto_rawDescOnce sync.Once
	file_snssai_proto_rawDescData = file_snssai_proto_rawDesc
)

func file_snssai_proto_rawDescGZIP() []byte {
	file_snssai_proto_rawDescOnce.Do(func() {
		file_snssai_proto_rawDescData = protoimpl.X.CompressGZIP(file_snssai_proto_rawDescData)
	})
	return file_snssai_proto_rawDescData
}

var file_snssai_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_snssai_proto_goTypes = []interface{}{
	(*Snssai)(nil), // 0: go_package.protos.Snssai
}
var file_snssai_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snssai_proto_init() }
func file_snssai_proto_init() {
	if File_snssai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snssai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snssai); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snssai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snssai_proto_goTypes,
		DependencyIndexes: file_snssai_proto_depIdxs,
		MessageInfos:      file_snssai_proto_msgTypes,
	}.Build()
	File_snssai_proto = out.File
	file_snssai_proto_rawDesc = nil
	file_snssai_proto_goTypes = nil
	file_snssai_proto_depIdxs = nil
}
