version: "3.7"

services:

  magmalte:
    image: mehuljindalwavelabs/nms-magmalte
    ports:
      - "8081:8081"
    environment:
      API_CERT_FILENAME: /run/secrets/api_cert
      API_PRIVATE_KEY_FILENAME: /run/secrets/api_key
      API_HOST: ${API_HOST:-nginx:9443}
      PORT: 8081
      HOST: 0.0.0.0
      MYSQL_HOST: postgres
      MYSQL_PORT: 5432
      MYSQL_DB: db_name
      MYSQL_USER: db_user
      MYSQL_PASS: db_password
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN:-}
      MYSQL_DIALECT: postgres
      PUPPETEER_SKIP_DOWNLOAD: "true"
    command: "/usr/local/bin/wait-for-it.sh -s -t 30 postgres:5432 -- yarn run start:dev"
    volumes:
      - /magma/magmalte/api:/usr/src/api
      - /magma/magmalte/app:/usr/src/app
      - /magma/magmalte/config:/usr/src/config
      - /magma/magmalte/generated:/usr/src/generated
      - /magma/magmalte/scripts:/usr/src/scripts
      - /magma/magmalte/server:/usr/src/server
      - /magma/magmalte/shared:/usr/src/shared
    secrets:
      - api_cert
      - api_key
    deploy:
      placement:
        constraints: [node.labels.metrics == true]

  nginx-proxy:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - /magma/docker_ssl_proxy:/etc/nginx/conf.d
    depends_on:
      - magmalte
    deploy:
      placement:
        constraints: [node.labels.metrics == true]

secrets:
  api_cert:
    file: /magma/certs/admin_operator.pem
  api_key:
    file: /magma/certs/admin_operator.key.pem