version: "3.7"

services:
  controller:
    image: mehuljindalwavelabs/orc8r_controller
    environment:
      TEST_MODE: "0"
      SERVICE_HOSTNAME: localhost
      SQL_DRIVER: postgres
      DATABASE_SOURCE: "dbname=db_name user=db_user password=db_password host=postgres sslmode=disable"
      SQL_DIALECT: psql
      SERVICE_REGISTRY_MODE: yaml
      MAGMA_PRINT_GRPC_PAYLOAD: 0
    volumes:
      - /magma/certs:/var/opt/magma/certs
      - /magma/controller/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    links:
      - fluentd
    depends_on:
      - fluentd
    command: ["/bin/sh", "-c", "/usr/local/bin/wait-for-it.sh -s -t 30 postgres:5432 && /usr/bin/supervisord"]
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.controller == true]
  nginx:
    image: mehuljindalwavelabs/orc8r_nginx
    ports:
      - 7443:8443/tcp   # controller GRPC port
      - 7444:8444/tcp  # Bootstrapper port
      - 9443:9443/tcp  # API/controller port
    environment:
      CONTROLLER_HOSTNAME: controller.domain.com
      PROXY_BACKENDS: controller  # Uses Docker internal DNS for controller
      TEST_MODE: "0"
      RESOLVER: "127.0.0.11"
      SERVICE_REGISTRY_MODE: yaml
      SSL_CERTIFICATE: "/var/opt/magma/certs/controller.crt"
      SSL_CERTIFICATE_KEY: "/var/opt/magma/certs/controller.key"
      SSL_CLIENT_CERTIFICATE: "/var/opt/magma/certs/certifier.pem"
    volumes:
      - /magma/certs:/var/opt/magma/certs
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.controller == true]
    depends_on:
      - controller

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.labels.controller == true]


  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
      - 5601:5601
    links:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.labels.controller == true]


  fluentd:
    image: mehuljindalwavelabs/orc8r_fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
      - 24225:24225
      - 24225:24225/udp
    volumes:
      - /magma/fluentd/conf:/fluentd/etc
      - /magma/certs:/var/opt/magma/certs
    deploy:
      placement:
        constraints: [node.labels.controller == true]

  postgres:
    image: postgres
    # Default is 64mb
    # Ref: https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container
    shm_size: '8192mb'
    ports:
      - "5432:5432/tcp"
    volumes:
      - /magma/postgres:/var/lib/postgresql/data
      #- pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    command:
      - "postgres"
      - "-c"
      - "log_duration=true"
#      - "-c"
#      - "log_statement=all"
#    restart: always
    deploy:
      placement:
        constraints: [node.labels.controller == true]

volumes:
  elasticsearch:
  #pgdata:
