# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "../wldistro_deploy", "/opt/wldistro_deploy"

  config.vm.define :wldistro, autostart: false do |wldistro|
    wldistro.vm.hostname = "WL-DISTRO-VM"
    wldistro.vm.network "private_network", ip: "192.168.60.171", nic_type: "82540EM"
    wldistro.vm.network "private_network", ip: "192.168.129.1", nic_type: "82540EM"

    wldistro.vm.provider "virtualbox" do |vb|
      vb.name = "wldistrouplift"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end
